cmake_minimum_required(VERSION 3.22.1)
project(neconyan)
set(CMAKE_CXX_STANDARD 20)
add_library(node SHARED IMPORTED)
set_target_properties(node PROPERTIES IMPORTED_LOCATION "${NODE_MOBILE_ROOT}/bin/${ANDROID_ABI}/libnode.so")
add_library(neconyan-node SHARED native.cpp)
target_include_directories(neconyan-node PRIVATE "${NODE_MOBILE_ROOT}/include/node")
target_link_libraries(neconyan-node node log)
target_link_options(neconyan-node PRIVATE "-Wl,-z,max-page-size=16384")
